//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicket.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db0c08f50393a241e58194a7d000e43d75Entities : DbContext
    {
        public db0c08f50393a241e58194a7d000e43d75Entities()
            : base("name=db0c08f50393a241e58194a7d000e43d75Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Company_Principal> Company_Principal { get; set; }
        public virtual DbSet<Principal> Principal { get; set; }
        public virtual DbSet<Principal_Product> Principal_Product { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketState> TicketState { get; set; }
        public virtual DbSet<TicketType> TicketType { get; set; }
    }
}
