//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicket.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int PrincipalId { get; set; }
        public int ProductId { get; set; }
        public string Details { get; set; }
        public string FileInfo { get; set; }
        public int StateId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> AssigneeId { get; set; }
    }
}
